### ISSUE TITLE
loading the package Bug!

### ISSUE THREAD

**Issue by ArchiBC** [asc-community/AngouriMath#620]
**The version I use **: 1.3.0 &1.4.0-1.4.0-preview.3

**Unexpected behaviour or bug**: 
The following error was encountered while loading the package。

Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
---> System.MissingMethodException: Method not found: 'Microsoft.DotNet.Interactive.DisplayedValue Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(Microsoft.DotNet.Interactive.KernelInvocationContext, System.Object, System.String)'.
at AngouriMath.InteractiveExtension.KernelExtension.Microsoft.DotNet.Interactive.IKernelExtension.OnLoadAsync(Kernel _arg1)
at Microsoft.DotNet.Interactive.App.PackageDirectoryExtensionLoader.LoadFromAssemblyFile(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\dotnet-interactive\PackageDirectoryExtensionLoader.cs:line 124
--- End of inner exception stack trace ---

![image](https://github.com/asc-community/AngouriMath/assets/53935289/0bcaeb36-fe75-47c6-a26e-2858bfcf536e)

**Comment by WhiteBlackGoose** [comment]
.NET Interactive wasn't stable back when that package was released, I don't know the state of things as of right now. It could be that they changed the API (at least as far as I see in the error). One solution would be to install the .NET Interactive of the suitable version or adjust AngouriMath.Interactive's code.

**Comment by baicai-design** [comment]
I tried setting the .net interactive version, but it doesn't seem to work, it still shows the same error.
It's a bit too hard for me to change the code.
![image](https://github.com/asc-community/AngouriMath/assets/53935289/4f45b013-7f20-4071-b503-fe977c848529)

**Comment by WhiteBlackGoose** [comment]
Well, did you set it to the relevant version? [Here](https://github.com/asc-community/AngouriMath/blob/master/Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj) is where versions are defined. You can probably try `1.0.0-beta.21606.1`, but no idea if it'd work

**Comment by baicai-design** [comment]
Nothing is useful after trying. Looks like I need to look into how to update the code.

**Comment by baicai-design** [comment]
I tried updating the dependent version and now it works successfully。I submitted a pull request to the main branch。

**Comment by Happypig375** [comment]
I assume this is now fixed for 1.4 with the PR merge and package updates.
